# -*- coding: utf-8 -*-
"""Top 10 Products by Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15SaY-0XrxrO0_5PgDMekXKX-cmqEvFPr
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_excel("Sample - Superstore.xlsx", sheet_name="RawData")

# Check the data
print(df.head())
print(df.columns)

# Group sales by product name
product_sales = (
    df.groupby("Product Name", as_index=False)["Sales"]
    .sum()
)

# Sort sales in descending order
product_sales = product_sales.sort_values(
    by="Sales",
    ascending=False
)

# Select the top 10 products
top_10 = product_sales.head(10)

print(top_10.to_string(index=False))

plt.figure(figsize=(12, 7))

plt.barh(top_10["Product Name"], top_10["Sales"])

plt.title("Top 10 Products by Sales")
plt.xlabel("Total Sales")
plt.ylabel("Product Name")

plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

top_10.to_csv("Top_10_Products_by_Sales.csv", index=False)

plt.figure(figsize=(12, 7))
plt.barh(top_10["Product Name"], top_10["Sales"])
plt.title("Top 10 Products by Sales")
plt.xlabel("Total Sales")
plt.ylabel("Product Name")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("Top_10_Products_Chart.png", dpi=300, bbox_inches="tight")
plt.show()

files.download("Top_10_Products_by_Sales.csv")

files.download("Top_10_Products_Chart.png")